### ISSUE TITLE
Explore LSL vs Brainflow

### ISSUE THREAD

**Issue by gupta-parth** [NTX-McGill/Neurotech-2023#2]
Look at pylsl and compare it with Brainflow. Write a python script that takes synthetic OpenBCI streams and logs it with both technologies. Some questions to think about and answer:

- Which technology is easier to use? How hard is it to setup etc. 
- Which has more features?

**Comment by Evarxsto** [comment]
Feb. 12 - Completed exploration. Comparison document can be found here https://docs.google.com/document/d/15LwxeHW2_DzEZJtz9X5SmOyNSfN1QYVyeHfKPrK-nOI/edit?usp=sharing
